<a href="https://colab.research.google.com/github/k00sharath/hello-world/blob/master/naive_bayes%20from%20scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***Implementing naive bayes from scratch***
# step1 seperating the dataset by class
# step 2 summarizing the dataset (mean,std) by particular attribute across each  class
# step 3: calculating the probabilities


In [103]:
from sklearn.datasets import load_iris
iris=load_iris()
iris_data=iris['data']
print(len(iris_data),type(iris_data),iris_data[:,1],len(iris['data']))

150 <class 'numpy.ndarray'> [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ] 150


In [112]:
import random
def crossval_split(data,targets,folds):
    train={}
    cross_val={}
    train_targets={}
    cross_val_targets={}
    indices=[]
    for i in range(len(data)):
        indices.append(i)
    indices_copy=[i for i in indices]

    size=len(data)/folds
    for i in range(folds):
        cross_val[i]=[]
        cross_val_targets[i]=[]
        for j in range(int(size)):
            indice=random.choice(indices)
            cross_val[i].append(data[indice])
            cross_val_targets[i].append(targets[indice])
            indices.remove(indice)
        train[i]=[data[i] for i in indices]
        train_targets[i]=[targets[i] for i in indices]
        indices=[i for i in range(len(data))]
    return(train,train_targets,cross_val,cross_val_targets)

crosssval_split(iris['data'],iris['target'],3)
                   


({0: [array([5.1, 3.5, 1.4, 0.2]),
   array([5. , 3.6, 1.4, 0.2]),
   array([5.4, 3.9, 1.7, 0.4]),
   array([4.6, 3.4, 1.4, 0.3]),
   array([4.9, 3.1, 1.5, 0.1]),
   array([5.4, 3.7, 1.5, 0.2]),
   array([4.8, 3.4, 1.6, 0.2]),
   array([5.8, 4. , 1.2, 0.2]),
   array([5.7, 4.4, 1.5, 0.4]),
   array([5.4, 3.9, 1.3, 0.4]),
   array([5.1, 3.8, 1.5, 0.3]),
   array([5.4, 3.4, 1.7, 0.2]),
   array([4.6, 3.6, 1. , 0.2]),
   array([5. , 3. , 1.6, 0.2]),
   array([5. , 3.4, 1.6, 0.4]),
   array([5.2, 3.4, 1.4, 0.2]),
   array([4.7, 3.2, 1.6, 0.2]),
   array([4.8, 3.1, 1.6, 0.2]),
   array([5.4, 3.4, 1.5, 0.4]),
   array([5.2, 4.1, 1.5, 0.1]),
   array([5.5, 4.2, 1.4, 0.2]),
   array([4.9, 3.1, 1.5, 0.2]),
   array([4.9, 3.6, 1.4, 0.1]),
   array([4.4, 3. , 1.3, 0.2]),
   array([5. , 3.5, 1.3, 0.3]),
   array([4.4, 3.2, 1.3, 0.2]),
   array([5. , 3.5, 1.6, 0.6]),
   array([5.1, 3.8, 1.9, 0.4]),
   array([4.8, 3. , 1.4, 0.3]),
   array([4.6, 3.2, 1.4, 0.2]),
   array([5.3, 3.7, 1.5, 0.2]),
   ar

In [104]:
print(iris_data[:,1])
print(iris)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
    

In [105]:
def seperate_by_class(data,target):
    class_wise_data={}
    for i in range(len(data)):
        if target[i] not in class_wise_data:
            class_wise_data[target[i]]=[]
        class_wise_data[target[i]].append(data[i])
    return(class_wise_data)



In [106]:
def mean(column_wise_data):
    sum=0
    for i in range(len(column_wise_data)):
        sum=sum+column_wise_data[i]
    return(sum/(len(column_wise_data)))

                                                                                 #across a particular class


In [107]:
def std(column_wise_data):
    std=0
    avg=mean(column_wise_data)
    for i in range(len(column_wise_data)):
        std+=((column_wise_data[i]-avg)**2/float((len(column_wise_data)-1)))
    return(avg,std,len(column_wise_data))




In [114]:
import numpy as np

def summarize_by_attributes(class_wise_data): 
    summary_class_wise={}
    for i in class_wise_data:
        if i not in summary_class_wise:
            summary_class_wise[i]=[]
        for j in range(len(class_wise_data[0][0])):
            column_wise_data=np.array(class_wise_data[i])

            summary_class_wise[i].append(std(column_wise_data[:,j]))
    return summary_class_wise


                                                                                #across a particular class

In [109]:
import numpy as np
class_wise_data=seperate_by_class(iris['data'],iris['target'])
column_wise_data=np.array(class_wise_data[0])
print(column_wise_data[:,1])
print(class_wise_data)
print(summarize_by_attribute(class_wise_data))

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3]
{0: [array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2]), array([4.6, 3.1, 1.5, 0.2]), array([5. , 3.6, 1.4, 0.2]), array([5.4, 3.9, 1.7, 0.4]), array([4.6, 3.4, 1.4, 0.3]), array([5. , 3.4, 1.5, 0.2]), array([4.4, 2.9, 1.4, 0.2]), array([4.9, 3.1, 1.5, 0.1]), array([5.4, 3.7, 1.5, 0.2]), array([4.8, 3.4, 1.6, 0.2]), array([4.8, 3. , 1.4, 0.1]), array([4.3, 3. , 1.1, 0.1]), array([5.8, 4. , 1.2, 0.2]), array([5.7, 4.4, 1.5, 0.4]), array([5.4, 3.9, 1.3, 0.4]), array([5.1, 3.5, 1.4, 0.3]), array([5.7, 3.8, 1.7, 0.3]), array([5.1, 3.8, 1.5, 0.3]), array([5.4, 3.4, 1.7, 0.2]), array([5.1, 3.7, 1.5, 0.4]), array([4.6, 3.6, 1. , 0.2]), array([5.1, 3.3, 1.7, 0.5]), array([4.8, 3.4, 1.9, 0.2]), array([5. , 3. , 1.6, 0.2]), array([5. , 3.4, 1.6, 0.4]), array([5

In [125]:
from math import exp
from math import sqrt
from math import pi
def calculate_probabilities(x_column,mean,std):
    gaussian_probability=(exp(-(x_column-mean)**2/(2*std**2)))*sqrt(1/(2*pi))*(1/std)
    return gaussian_probability
def predict_class(test_example,summary):
    probabilities={}
    for i in summary:
        prob=(summary[i][1][2])/(sum(summary[i][1][2] for i in summary))
        for j,c in enumerate(summary[i]):
            prob=prob*calculate_probabilities(test_example[j],c[0],c[1])
        probabilities[i]=prob
    return probabilities
def predictions(test_data,summary):
    predictions=[]
    for i in range(len(test_data)):
        probs=predict_class(test_data[i],summary)
        predictions.append(max(probs,key=probs.get))
    return predictions

    
def accuracy(predictions,targets):
    correct=0
    for i in range(len(targets)):
        if targets[i]==predictions[i]:
            correct=correct+1
    return((correct/len(targets))*100)
         
    
        




In [133]:
def naive_bayes_model(cross_val,cross_val_targets,train,train_targets):
    for i in train:
        seperated_data=seperate_by_class(train[i],train_targets[i])
        summary=summarize_by_attributes(seperated_data)
        predictions_from_model=predictions(cross_val[i],summary)
        accuracy_from_model=accuracy(predictions_from_model,cross_val_targets[i])
        print('Accuracy for fold',i,'is',accuracy_from_model)
train,train_targets,cross_val,cross_val_targets=crossval_split(iris['data'],iris['target'],3)

naive_bayes_model(cross_val,cross_val_targets,train,train_targets)       




Accuracy for fold 0 is 96.0
Accuracy for fold 1 is 92.0
Accuracy for fold 2 is 88.0
